
//! Autogenerated weights for `pallet_rootdns`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-05-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `pop-os`, CPU: `11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/node-template
// benchmark
// pallet
// --wasm-execution=compiled
// --pallet
// pallet_rootdns
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./pallets/rootdns/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_rootdns`.
pub trait WeightInfo {
	fn benchmark_register_tld() -> Weight;
	fn benchmark_remove_tld() -> Weight;
}
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `RootDNSModule::TLDMap` (r:1 w:1)
	/// Proof: `RootDNSModule::TLDMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn benchmark_register_tld() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3471`
		// Minimum execution time: 13_046_000 picoseconds.
		Weight::from_parts(13_974_000, 0)
			.saturating_add(Weight::from_parts(0, 3471))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `RootDNSModule::TLDMap` (r:1 w:1)
	/// Proof: `RootDNSModule::TLDMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn benchmark_remove_tld() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `95`
		//  Estimated: `3560`
		// Minimum execution time: 13_783_000 picoseconds.
		Weight::from_parts(14_328_000, 0)
			.saturating_add(Weight::from_parts(0, 3560))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
