
//! Autogenerated weights for `pallet_tld`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-01-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `pop-os`, CPU: `11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_tld
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/tld/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_tld`.
pub trait WeightInfo {
	fn benchmark_register_domain() -> Weight;
	fn benchmark_amend_chainspec() -> Weight;
	fn benchmark_revoke_domain() -> Weight;
	fn benchmark_initiate_transfer() -> Weight;
	fn benchmark_accept_transfer() -> Weight;
	fn benchmark_revoke_transfer() -> Weight;
}
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TldModule::DomainMap` (r:1 w:1)
	/// Proof: `TldModule::DomainMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TldModule::DomainExpiry` (r:0 w:1)
	/// Proof: `TldModule::DomainExpiry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn benchmark_register_domain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3471`
		// Minimum execution time: 16_265_000 picoseconds.
		Weight::from_parts(18_188_000, 0)
			.saturating_add(Weight::from_parts(0, 3471))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TldModule::DomainMap` (r:1 w:1)
	/// Proof: `TldModule::DomainMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn benchmark_amend_chainspec() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `153`
		//  Estimated: `3618`
		// Minimum execution time: 16_470_000 picoseconds.
		Weight::from_parts(16_921_000, 0)
			.saturating_add(Weight::from_parts(0, 3618))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TldModule::DomainMap` (r:1 w:1)
	/// Proof: `TldModule::DomainMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TldModule::DomainExpiry` (r:0 w:1)
	/// Proof: `TldModule::DomainExpiry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn benchmark_revoke_domain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `153`
		//  Estimated: `3618`
		// Minimum execution time: 16_132_000 picoseconds.
		Weight::from_parts(16_706_000, 0)
			.saturating_add(Weight::from_parts(0, 3618))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TldModule::DomainMap` (r:1 w:0)
	/// Proof: `TldModule::DomainMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TldModule::PendingTransfers` (r:1 w:1)
	/// Proof: `TldModule::PendingTransfers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn benchmark_initiate_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `158`
		//  Estimated: `3623`
		// Minimum execution time: 17_092_000 picoseconds.
		Weight::from_parts(19_407_000, 0)
			.saturating_add(Weight::from_parts(0, 3623))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TldModule::PendingTransfers` (r:1 w:1)
	/// Proof: `TldModule::PendingTransfers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TldModule::DomainMap` (r:1 w:1)
	/// Proof: `TldModule::DomainMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn benchmark_accept_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `240`
		//  Estimated: `3705`
		// Minimum execution time: 22_408_000 picoseconds.
		Weight::from_parts(23_010_000, 0)
			.saturating_add(Weight::from_parts(0, 3705))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TldModule::DomainMap` (r:1 w:0)
	/// Proof: `TldModule::DomainMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TldModule::PendingTransfers` (r:1 w:1)
	/// Proof: `TldModule::PendingTransfers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn benchmark_revoke_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `240`
		//  Estimated: `3705`
		// Minimum execution time: 20_235_000 picoseconds.
		Weight::from_parts(22_616_000, 0)
			.saturating_add(Weight::from_parts(0, 3705))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
