
//! Autogenerated weights for `pallet_tld`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-05-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `pop-os`, CPU: `11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/node-template
// benchmark
// pallet
// --wasm-execution=compiled
// --pallet
// pallet_tld
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./pallets/tld/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_tld`.
pub trait WeightInfo {
	fn benchmark_register_domain() -> Weight;
	fn benchmark_amend_chainspec() -> Weight;
	fn benchmark_revoke_domain() -> Weight;
	fn benchmark_initiate_transfer() -> Weight;
	fn benchmark_accept_transfer() -> Weight;
	fn benchmark_revoke_transfer() -> Weight;
	fn benchmark_send_heartbeat() -> Weight;
	fn benchmark_report_missed_heartbeat() -> Weight;
}
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TldModule::DomainMap` (r:1 w:1)
	/// Proof: `TldModule::DomainMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TldModule::DomainExpiry` (r:0 w:1)
	/// Proof: `TldModule::DomainExpiry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TldModule::MaintainerMap` (r:0 w:1)
	/// Proof: `TldModule::MaintainerMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn benchmark_register_domain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3471`
		// Minimum execution time: 24_164_000 picoseconds.
		Weight::from_parts(25_980_000, 0)
			.saturating_add(Weight::from_parts(0, 3471))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `TldModule::DomainMap` (r:1 w:1)
	/// Proof: `TldModule::DomainMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TldModule::DomainExpiry` (r:1 w:0)
	/// Proof: `TldModule::DomainExpiry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn benchmark_amend_chainspec() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `207`
		//  Estimated: `3672`
		// Minimum execution time: 29_927_000 picoseconds.
		Weight::from_parts(38_333_000, 0)
			.saturating_add(Weight::from_parts(0, 3672))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TldModule::DomainMap` (r:1 w:1)
	/// Proof: `TldModule::DomainMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TldModule::DomainExpiry` (r:0 w:1)
	/// Proof: `TldModule::DomainExpiry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TldModule::MaintainerMap` (r:0 w:1)
	/// Proof: `TldModule::MaintainerMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn benchmark_revoke_domain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `3656`
		// Minimum execution time: 29_876_000 picoseconds.
		Weight::from_parts(35_241_000, 0)
			.saturating_add(Weight::from_parts(0, 3656))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `TldModule::DomainMap` (r:1 w:0)
	/// Proof: `TldModule::DomainMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TldModule::PendingTransfers` (r:1 w:1)
	/// Proof: `TldModule::PendingTransfers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn benchmark_initiate_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `3656`
		// Minimum execution time: 34_451_000 picoseconds.
		Weight::from_parts(35_866_000, 0)
			.saturating_add(Weight::from_parts(0, 3656))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TldModule::PendingTransfers` (r:1 w:1)
	/// Proof: `TldModule::PendingTransfers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TldModule::DomainMap` (r:1 w:1)
	/// Proof: `TldModule::DomainMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn benchmark_accept_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `269`
		//  Estimated: `3734`
		// Minimum execution time: 38_814_000 picoseconds.
		Weight::from_parts(41_545_000, 0)
			.saturating_add(Weight::from_parts(0, 3734))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TldModule::DomainMap` (r:1 w:0)
	/// Proof: `TldModule::DomainMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TldModule::PendingTransfers` (r:1 w:1)
	/// Proof: `TldModule::PendingTransfers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn benchmark_revoke_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `269`
		//  Estimated: `3734`
		// Minimum execution time: 33_176_000 picoseconds.
		Weight::from_parts(38_208_000, 0)
			.saturating_add(Weight::from_parts(0, 3734))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TldModule::DomainMap` (r:1 w:1)
	/// Proof: `TldModule::DomainMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TldModule::DomainExpiry` (r:0 w:1)
	/// Proof: `TldModule::DomainExpiry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn benchmark_send_heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `3656`
		// Minimum execution time: 26_412_000 picoseconds.
		Weight::from_parts(29_019_000, 0)
			.saturating_add(Weight::from_parts(0, 3656))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TldModule::DomainMap` (r:1 w:0)
	/// Proof: `TldModule::DomainMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TldModule::HeartbeatObservations` (r:1 w:1)
	/// Proof: `TldModule::HeartbeatObservations` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TldModule::HeartbeatObservationCount` (r:1 w:1)
	/// Proof: `TldModule::HeartbeatObservationCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn benchmark_report_missed_heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `217`
		//  Estimated: `3682`
		// Minimum execution time: 40_428_000 picoseconds.
		Weight::from_parts(43_352_000, 0)
			.saturating_add(Weight::from_parts(0, 3682))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
