
//! Autogenerated weights for `pallet_assetdiscovery`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-05-09, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `pop-os`, CPU: `11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/node-template
// benchmark
// pallet
// --wasm-execution=compiled
// --pallet
// pallet_assetdiscovery
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./pallets/assetdiscovery/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_assetdiscovery`.
pub trait WeightInfo {
	fn submit_verified_domain() -> Weight;
	fn register_asset_for_domain() -> Weight;
	fn cleanup_revoked_domains() -> Weight;
	fn remove_expired_pending_requests() -> Weight;
	fn vote_for_domain_revocation() -> Weight;
}
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `AssetDiscoveryModule::PendingRequests` (r:1 w:1)
	/// Proof: `AssetDiscoveryModule::PendingRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetDiscoveryModule::AssetProviders` (r:1 w:1)
	/// Proof: `AssetDiscoveryModule::AssetProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetDiscoveryModule::ProviderAssets` (r:1 w:1)
	/// Proof: `AssetDiscoveryModule::ProviderAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_verified_domain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `161`
		//  Estimated: `3626`
		// Minimum execution time: 25_465_000 picoseconds.
		Weight::from_parts(26_674_000, 0)
			.saturating_add(Weight::from_parts(0, 3626))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AssetDiscoveryModule::PendingRequests` (r:0 w:1)
	/// Proof: `AssetDiscoveryModule::PendingRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_asset_for_domain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 12_190_000 picoseconds.
		Weight::from_parts(13_443_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AssetDiscoveryModule::ProviderAssets` (r:1 w:1)
	/// Proof: `AssetDiscoveryModule::ProviderAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetDiscoveryModule::AssetProviders` (r:1 w:1)
	/// Proof: `AssetDiscoveryModule::AssetProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cleanup_revoked_domains() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `178`
		//  Estimated: `3643`
		// Minimum execution time: 20_263_000 picoseconds.
		Weight::from_parts(20_729_000, 0)
			.saturating_add(Weight::from_parts(0, 3643))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AssetDiscoveryModule::PendingRequests` (r:2 w:0)
	/// Proof: `AssetDiscoveryModule::PendingRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_expired_pending_requests() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `177`
		//  Estimated: `6117`
		// Minimum execution time: 15_301_000 picoseconds.
		Weight::from_parts(15_754_000, 0)
			.saturating_add(Weight::from_parts(0, 6117))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `AssetDiscoveryModule::ProviderAssets` (r:1 w:0)
	/// Proof: `AssetDiscoveryModule::ProviderAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetDiscoveryModule::RevocationVotes` (r:1 w:1)
	/// Proof: `AssetDiscoveryModule::RevocationVotes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn vote_for_domain_revocation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140`
		//  Estimated: `3605`
		// Minimum execution time: 18_743_000 picoseconds.
		Weight::from_parts(19_501_000, 0)
			.saturating_add(Weight::from_parts(0, 3605))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
